add_newline = true

# Basic start
[character]
error_symbol = "[â¯](red)"
success_symbol = "[â¯](purple)"
vicmd_symbol = "[â®](green)"

[cmd_duration]
min_time = 500

[directory]
disabled = false
style = "bold cyan"
truncate_to_repo = true
truncation_length = 6

[hostname]
disabled = false
ssh_only = false
trim_at = "."

[line_break]
disabled = false

[username]
disabled = false
show_always = false
style_root = "bold red"
style_user = "bold yellow"

[package]
disabled = true
# Basic end

# System info start 
[battery]
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"
full_symbol = "ğŸ”‹"

[[battery.display]]
style = "bold red"
threshold = 10

[[battery.display]]
style = "bold yellow"
threshold = 60

[[battery.display]]
style = "bold green"
threshold = 100

[memory_usage]
disabled = false
format = "$symbol[${ram}( | ${swap})]($style) "
style = "bold dimmed white"
threshold = 70
# System info end

# Git start
[git_status]
conflicted = "â€‹"
deleted = "â€‹"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
modified = "â€‹"
renamed = "â€‹"
staged = "â€‹"
stashed = "â‰¡"
style = "cyan"
untracked = "â€‹"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
# Git end

# Langauge start
[nodejs]
disabled = false
style = "bold green"
symbol = "â¬¢ "

[python]
disabled = false
format = "[$virtualenv]($style) "
pyenv_prefix = "pyenv"
pyenv_version_name = false
style = "bright-black"
symbol = "ğŸ "
# Language end
